name: 'action-terraform-module-updates'
description: 'Check if there is an update available for the terraform modules used in your repo. (based on dependabot)'
author: 'pmckl'
inputs:
  directory:
    description: >
      Where to look for terraform files to check for dependency upgrades.
      The directory is relative to the repository's root.
      Multiple paths can be provided by splitting them with a new line.
      Example:
        directory: |
          /path/to/first/module
          /path/to/second/module
    default: "/"
    required: false
  token:
    description: >
      Auth token used to create pull-request comment.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: false
  github_dependency_token:
    description: >
      Auth token used for checking terraform dependencies that are from github repositories.
      Token requires read access to all modules that you want to automatically check for updates
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: false
  gh_context:
    default: ${{ toJSON(github) }}

runs:
  using: 'docker'
  #image: 'docker://pmckl/action-terraform-module-updates:latest'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'orange'