---
name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: build container
        run: docker build -t action-terraform-module-updates:${{ steps.version.outputs.new_tag }} .
      - run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: tag and push
        run: |
          docker tag action-terraform-module-updates:${{ steps.version.outputs.new_tag }} pmckl/action-terraform-module-updates:${{ steps.version.outputs.new_tag }}
          docker tag action-terraform-module-updates:${{ steps.version.outputs.new_tag }} pmckl/action-terraform-module-updates:latest
          
          docker push pmckl/action-terraform-module-updates:${{ steps.version.outputs.new_tag }}
          docker push pmckl/action-terraform-module-updates:latest
      - name: Patch action.yaml
        runs: |
          export IMG_VERSION="pmckl/action-terraform-module-updates:${{ steps.version.outputs.new_tag }}"
          yq -e -i '.runs.image=env(IMG_VERSION)' action.yml
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add action.yml
          git commit -m "(chore) updating image version in action.yml" || echo "No changes to commit"
          git push origin HEAD:master
      - name: Generate release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --title "${{ steps.version.outputs.new_tag }}" \
            "${{ steps.version.outputs.new_tag }}" \
            --generate-notes